app_aleatorio4:
    path: /num-aleatorios/num4
    controller: App\Controller\AleatorioController::index3
    methods: 

app_hola:
    path: /hola2/{nombre}/{apellido}
    controller: App\Controller\HolaController::index
    methods: GET