# Para poner una ruta. OJO, ponerla al COMPLETO!
app_aleatorio2:
    path: /num2
    controller: App\Controller\AleatorioController::index2
    methods: GET | POST

app_aleatorio3:
    path: /num3
    controller: App\Controller\AleatorioController::index3
    methods: GET 

app_aleatorio4:
    path: /num4
    controller: App\Controller\AleatorioController::index3
    methods: GET 